### ISSUE TITLE
Bug: en linea 24 error

### ISSUE THREAD

**Issue by sabas1080** [sabas1080/cursodegit#1]
Hola Equipo

Probando la aplicacion, en la linea 24 aparece un error

`syntaxys error:
delay(100);
pinMode(9,LOW);
`
@Armadillo117 @capuchino69 @Soulkrown @Jorgeuri

**Comment by Armadillo117** [comment]
primer comentario!!!!
saludame :v

**Comment by Fabian-RC** [comment]
pa khe kieres saber eso jaja saludos!!

**Comment by sabas1080** [comment]
- [x] Verificar codigo en Arduino UNO
- [ ] Vaidar codigo
- [x] Verificar codigo en Arduino Nano

**Comment by Soulkrown** [comment]
Que onda!
